name: oua_flutter_travel_gallery
description: Travel Gallery is a mobile application prepared with flutter for Bootcamp 2024 of OUA.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

 
  uses-material-design: true

  
