name: oua_flutter_travel_gallery
description: Travel Gallery is a mobile application prepared with flutter for Bootcamp 2024 of OUA.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  
  flutter_signin_button: ^2.0.0

  http: ^0.13.5
  cached_network_image: ^3.2.3

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

  assets:
      - assets/images/

 
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-SemiBold.ttf
         - asset: assets/fonts/Poppins-Regular.ttf
     - family: Rowdies
       fonts:
         - asset:  assets/fonts/Rowdies-Regular.ttf
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Medium.ttf
         - asset: assets/fonts/Roboto-MediumItalic.ttf
         - asset: assets/fonts/Roboto-Regular.ttf
 
  uses-material-design: true

  
